site_name: My Docs
theme: readthedocs
plugins:
pages:
    - 面试官问我：说说你对浏览器缓存的理解: 面试官问我：说说你对浏览器缓存的理解.md
    - 如何精准地在 GitHub 搜索项目: 如何精准地在 GitHub 搜索项目.md
    - 已上岸字节，整理一波测开面经_笔经面经_牛客网: 已上岸字节，整理一波测开面经_笔经面经_牛客网.md
    - 程序员跳槽时，如何优雅地谈薪水: 程序员跳槽时，如何优雅地谈薪水.md
    - index: index.md
    - 测试常见问题合集 - anliux - 博客园: 测试常见问题合集 - anliux - 博客园.md
    - 云端 IDE: 云端 IDE.md
    - 详解 MySQL 基准测试和 sysbench 工具: 详解 MySQL 基准测试和 sysbench 工具.md
    - Git-ComdLine-REST: Git-ComdLine-REST.md
    - ADB 操作命令详解及用法大全: ADB 操作命令详解及用法大全.md
    - MIT6.824 分布式系统课程中文翻译: MIT6.824 分布式系统课程中文翻译.md
    - 个人吐血系列 - 总结 MySQL: 个人吐血系列 - 总结 MySQL.md
    - BenchmarkSQL5.0 数据库 TPC-C 基准测试 - 瑾熙的博客 JL Blog: BenchmarkSQL5.0 数据库 TPC-C 基准测试 - 瑾熙的博客 JL Blog.md
    - HTTP 各版本特性及区别: HTTP 各版本特性及区别.md
    - 前后端分离常用的认证方式: 前后端分离常用的认证方式.md
    - MkDocs 构建你自己的知识库: MkDocs 构建你自己的知识库.md
    - mysql-index: mysql-index.md
    - 面试常问智力题: 面试常问智力题.md
    - mysql-transaction: mysql-transaction.md
    - 书写高质量 SQL 的 30 条建议: 书写高质量 SQL 的 30 条建议.md
    - 使用 benchmarkSQL 测试数据库的 TPCC - konglingbin - 博客园: 使用 benchmarkSQL 测试数据库的 TPCC - konglingbin - 博客园.md
    - 47 张图带你 MySQL 进阶: 47 张图带你 MySQL 进阶.md
    - 史上最全的数据库面试题，不看绝对后悔_资源分享_牛客网: 史上最全的数据库面试题，不看绝对后悔_资源分享_牛客网.md
    - 中文文案排版指北: 中文文案排版指北.md
