# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 9 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies  # 安装python依赖包
      run: python -m pip install mkdocs
    - name: run test
      run: python test.py
#     - name: build
#       run: mkdocs build
    - name: Commit and push
      run: |-
        git config --global user.email "bot@github.com" && git config --global user.name "Bot"
        git diff
        git add . && git commit -m ":memo: mkdocs update" || exit 0
        git push 
